Feature/product description
DrugStoc/tpn-web pull request #44
Opened 2023-03-02 07:35 UTC by Akashakashpal

2023-03-02 09:40 UTC, dewale005 requested changes
Add the interfaces for this components

2023-03-02 09:40 UTC, dewale005 commented on src/components/LocationModal/LocationModal.tsx
>                    sx={{
you need to take the style out of the element

2023-03-02 10:13 UTC, Akashakashpal commented
working on it

2023-03-02 10:44 UTC, dewale005 requested changes
please address the styles done on the elements

2023-03-02 10:44 UTC, dewale005 commented on src/Layout/ProductHeader/ProductsHeader.tsx
> +      backgroundColor={{ base: 'FFFFFF', lg: '#F7F8F9' }}
this is another example of style in element

2023-03-02 10:44 UTC, dewale005 commented on src/components/LocationModal/LocationModal.tsx
> +        <ModalContent maxWidth={{ base: '19rem', lg: '47rem' }} p={3} pt={10}>
this is another example of style in element

2023-03-02 10:44 UTC, dewale005 commented on src/components/LocationModal/LocationModal.tsx
> +              fontSize={{ base: '10px', lg: '20px' }}
this is another example of style in element

2023-03-02 10:44 UTC, dewale005 commented on src/components/LocationModal/LocationModal.tsx
> +            top={{ base: '1.5rem', lg: '2rem' }}
this is another example of style in element

2023-03-02 10:44 UTC, dewale005 commented on src/components/LocationModal/LocationModal.tsx
> +                fontSize: { base: '13px', lg: '25px' },
this is another example of style in element

2023-03-02 10:44 UTC, dewale005 commented on src/components/LocationModal/LocationModal.tsx
>                <Divider />
this is another example of style in element

2023-03-03 04:40 UTC, dewale005 approved these changes

2023-03-03 04:40 UTC, merged